- name: sailor playbook
  hosts: all
  tasks:
  
  - name: open-jdk
    apt: 
      name: openjdk-11-jdk
    update_cache: true

  - name: create file
    file:
      path: /u01/middleware
      state: directory       
 
  - name: 
    grt_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz
      dest: /u01/middleware
      mode: 0755

  - name: unarchive
    unarchive:
      src: /u01/middleware/apache-tomcat-9.0.85.tar.gz
      dest: /u01/middleware
      remote_src: true

  - name: copy tomcat templete
    copy:
      src: src/main/config/ansible/tomcat.j2
      dest: /etc/systemd/system/tomcat.service
    become: yes  


